### ISSUE TITLE
any updates for recent kernel chtmax98090 driver?

### ISSUE THREAD

**Issue by cypa** [kcolford/lenovo-thinkpad-yoga-11e-chromebook#3]
I have problem with video playback - audio is too fast, I guess audio frequency is higher than it should be. See https://bugs.archlinux.org/task/48936
```

~λ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: chtmax98090 [chtmax98090], device 0: 1 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: chtmax98090 [chtmax98090], device 1: Deep-Buffer Audio (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: PCH [HDA Intel PCH], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: PCH [HDA Intel PCH], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

**Comment by kcolford** [comment]
I'm honestly going to direct you upstream for this issue. I have since retired this laptop and no longer use it. I did get sound working with Dean Wallace's kernel patch which is why I made it an optional dependency on the AUR which seems to have been upstreamed. I suggest you make on a comment on the archlinux bugtracker entry you've linked to see if anyone can help.

Let me know if you find anything!
